### PR TITLE
ansible playbooks now run based on app_type of request

### PR DESCRIPTION
**Pull request by jezhou8**

### CODE REVIEW

**Comment by LincolnBryant** [comment]
I think you can remove ```path = "/etc/vc3/vc3-playbooks/login/"``` on line 325 and simply use `self.ansible_path` which is already defined in the config file.

Also we can remove the comment on line 438 now.

**Comment by btovar** [comment]
Looks good. 

I modified the names for the recipes in vc3-playbook to login-htcondor.yaml and login-workqueue.yaml to match this.

Is there a way to have 'includes' in ansible?

**Review by btovar — APPROVED** [review]

**Comment by LincolnBryant** [comment]
@jezhou8  : Thanks for the patch! :100: 

@btovar :
Thanks for review. I am merging this.

Yes, I'm pretty sure we can do that. Are you thinking we need a "base" config and then have our middleware-specific specializations on top of that?.

**Comment by btovar** [comment]
Yes, that. Like accounts, cvmfs, motd, etc.

**Pull request merged**
